package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;

    private final JoinPredicate p;
    private final DbIterator child1, child2;
    private final Map<Integer, List<Tuple>> hash;
    private Tuple now;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.hash = new HashMap<>();
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public String getJoinField1Name() {
        int f = p.getField1();
        return child1.getTupleDesc().getFieldName(f);
    }

    public String getJoinField2Name() {
        int f = p.getField2();
        return child2.getTupleDesc().getFieldName(f);
    }

    private void init() throws TransactionAbortedException, DbException {
        while (child2.hasNext()) {
            Tuple now = child2.next();
            hash.computeIfAbsent(now.getField(p.getField2()).hashCode(), (k) -> new ArrayList<>()).add(now);
        }
    }
    
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        child1.open();
        child2.open();
        init();
        child2.close();
    }

    public void close() {
        super.close();
        child1.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        now = null;
        listIt = null;
    }

    transient Iterator<Tuple> listIt = null;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (true) {
            if (listIt != null && listIt.hasNext()) {
                Tuple t = listIt.next();
                Tuple ret = new Tuple(getTupleDesc());
                int cnt = 0;
                for (int i = 0; i < now.getTupleDesc().numFields(); i++)
                    ret.setField(cnt++, now.getField(i));
                for (int i = 0; i < t.getTupleDesc().numFields(); i++)
                    ret.setField(cnt++, t.getField(i));
                return ret;
            }
            if (!child1.hasNext()) return null;
            now = child1.next();
            List<Tuple> list = hash.get(now.getField(p.getField1()).hashCode());
            if (list == null) listIt = null;
            else listIt = list.iterator();
        }
    }

    @Override
    public DbIterator[] getChildren() {
        DbIterator[] children = new DbIterator[2];
        setChildren(children);
        return children;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        children[0] = child1;
        children[1] = child2;
    }

    
}
